/**
 * Спецификация свойств элементов формы: подпись и группа для узла XML.
 *
 * Состав свойств приходит от md-sparrow (он снимает его с модели формата), а как их назвать
 * и в какую группу положить - решает расширение: в самой модели этого нет.
 *
 * @module formItemPropertySpec
 */

/** Группы палитры в порядке показа; последняя собирает всё, чему группа не назначена. */
export const PROPERTY_GROUP_ORDER = [
	'Основные',
	'Использование',
	'Расположение',
	'Оформление',
	'Данные',
	'События',
	'Прочие',
] as const;

export type PropertyGroupName = (typeof PROPERTY_GROUP_ORDER)[number];

interface PropertySpec {
	readonly label: string;
	readonly group: PropertyGroupName;
}

/**
 * Подпись и группа для узла свойства. Русские названия те же, что в конфигураторе.
 * Чего здесь нет, палитра покажет под именем узла в группе «Прочие»: словарь свойств приходит
 * от модели формата и растёт вместе с платформой, поэтому список заведомо неполный и это нормально.
 */
const SPEC: Record<string, PropertySpec> = {
	name: { label: 'Имя', group: 'Основные' },
	id: { label: 'Идентификатор', group: 'Основные' },
	Title: { label: 'Заголовок', group: 'Основные' },
	TitleLocation: { label: 'Положение заголовка', group: 'Расположение' },
	TitleHeight: { label: 'Высота заголовка', group: 'Расположение' },
	TitleTextColor: { label: 'Цвет текста заголовка', group: 'Оформление' },
	TitleBackColor: { label: 'Цвет фона заголовка', group: 'Оформление' },
	TitleFont: { label: 'Шрифт заголовка', group: 'Оформление' },
	TitleDataPath: { label: 'Путь к данным заголовка', group: 'Данные' },
	ShowTitle: { label: 'Отображать заголовок', group: 'Основные' },
	DataPath: { label: 'Путь к данным', group: 'Данные' },
	Type: { label: 'Вид', group: 'Основные' },
	Kind: { label: 'Вид', group: 'Основные' },
	Visible: { label: 'Видимость', group: 'Использование' },
	UserVisible: { label: 'Пользовательская видимость', group: 'Использование' },
	Enabled: { label: 'Доступность', group: 'Использование' },
	ReadOnly: { label: 'Только просмотр', group: 'Использование' },
	SkipOnInput: { label: 'Пропускать при вводе', group: 'Использование' },
	DefaultItem: { label: 'Активизировать по умолчанию', group: 'Использование' },
	EnableContentChange: { label: 'Изменение состава', group: 'Использование' },
	DisplayImportance: { label: 'Важность при отображении', group: 'Использование' },
	ToolTip: { label: 'Подсказка', group: 'Основные' },
	ToolTipRepresentation: { label: 'Отображение подсказки', group: 'Оформление' },
	Width: { label: 'Ширина', group: 'Расположение' },
	Height: { label: 'Высота', group: 'Расположение' },
	AutoMaxWidth: { label: 'Автомаксимальная ширина', group: 'Расположение' },
	AutoMaxHeight: { label: 'Автомаксимальная высота', group: 'Расположение' },
	MaxWidth: { label: 'Максимальная ширина', group: 'Расположение' },
	MaxHeight: { label: 'Максимальная высота', group: 'Расположение' },
	HorizontalStretch: { label: 'Растягивать по горизонтали', group: 'Расположение' },
	VerticalStretch: { label: 'Растягивать по вертикали', group: 'Расположение' },
	HorizontalAlign: { label: 'Горизонтальное положение', group: 'Расположение' },
	VerticalAlign: { label: 'Вертикальное положение', group: 'Расположение' },
	GroupHorizontalAlign: { label: 'Горизонтальное положение в группе', group: 'Расположение' },
	GroupVerticalAlign: { label: 'Вертикальное положение в группе', group: 'Расположение' },
	Group: { label: 'Группировка', group: 'Расположение' },
	ChildrenAlign: { label: 'Выравнивание подчинённых', group: 'Расположение' },
	ChildItemsWidth: { label: 'Ширина подчинённых', group: 'Расположение' },
	ChildItemsTitleLocation: { label: 'Положение заголовков подчинённых', group: 'Расположение' },
	HorizontalSpacing: { label: 'Интервал по горизонтали', group: 'Расположение' },
	VerticalSpacing: { label: 'Интервал по вертикали', group: 'Расположение' },
	Representation: { label: 'Отображение', group: 'Оформление' },
	ControlRepresentation: { label: 'Отображение управления', group: 'Оформление' },
	Behavior: { label: 'Поведение', group: 'Использование' },
	Collapsed: { label: 'Свёрнута', group: 'Использование' },
	United: { label: 'Объединять', group: 'Оформление' },
	ShowLeftMargin: { label: 'Отображать левый отступ', group: 'Оформление' },
	BackColor: { label: 'Цвет фона', group: 'Оформление' },
	TextColor: { label: 'Цвет текста', group: 'Оформление' },
	BorderColor: { label: 'Цвет рамки', group: 'Оформление' },
	Border: { label: 'Рамка', group: 'Оформление' },
	Font: { label: 'Шрифт', group: 'Оформление' },
	Picture: { label: 'Картинка', group: 'Оформление' },
	Shortcut: { label: 'Сочетание клавиш', group: 'Использование' },
	CommandName: { label: 'Имя команды', group: 'Данные' },
	CommandSet: { label: 'Состав команд', group: 'Данные' },
	FunctionalOptions: { label: 'Функциональные опции', group: 'Использование' },
	EditMode: { label: 'Режим редактирования', group: 'Использование' },
	FixingInTable: { label: 'Фиксация в таблице', group: 'Расположение' },
	AutoCellHeight: { label: 'Автовысота ячейки', group: 'Расположение' },
	CellHyperlink: { label: 'Гиперссылка ячейки', group: 'Оформление' },
	ShowInHeader: { label: 'Отображать в шапке', group: 'Использование' },
	ShowInFooter: { label: 'Отображать в подвале', group: 'Использование' },
	FooterText: { label: 'Текст подвала', group: 'Данные' },
	FooterDataPath: { label: 'Путь к данным подвала', group: 'Данные' },
	MarkNegatives: { label: 'Выделять отрицательные', group: 'Оформление' },
	Format: { label: 'Формат', group: 'Оформление' },
	EditFormat: { label: 'Формат редактирования', group: 'Оформление' },
	Mask: { label: 'Маска', group: 'Использование' },
	PasswordMode: { label: 'Режим пароля', group: 'Использование' },
	MultiLine: { label: 'Многострочный режим', group: 'Использование' },
	ExtendedEdit: { label: 'Расширенное редактирование', group: 'Использование' },
	ChoiceList: { label: 'Список выбора', group: 'Данные' },
	ChoiceForm: { label: 'Форма выбора', group: 'Данные' },
	QuickChoice: { label: 'Быстрый выбор', group: 'Использование' },
	ChoiceFoldersAndItems: { label: 'Выбор групп и элементов', group: 'Использование' },
	ChoiceParameters: { label: 'Параметры выбора', group: 'Данные' },
	ChoiceParameterLinks: { label: 'Связи параметров выбора', group: 'Данные' },
	CreateButton: { label: 'Кнопка создания', group: 'Использование' },
	ClearButton: { label: 'Кнопка очистки', group: 'Использование' },
	ChoiceButton: { label: 'Кнопка выбора', group: 'Использование' },
	OpenButton: { label: 'Кнопка открытия', group: 'Использование' },
	SpinButton: { label: 'Кнопка регулирования', group: 'Использование' },
	TypeLink: { label: 'Связь по типу', group: 'Данные' },
	TypeRestriction: { label: 'Ограничение типа', group: 'Данные' },
	AutoMarkIncomplete: { label: 'Автоотметка незаполненного', group: 'Использование' },
	MarkIncomplete: { label: 'Отметка незаполненного', group: 'Использование' },
	WarningOnEdit: { label: 'Предупреждение при редактировании', group: 'Использование' },
	WarningOnEditRepresentation: { label: 'Отображение предупреждения', group: 'Использование' },

	MinWidth: { label: 'Минимальная ширина', group: 'Расположение' },
	MinHeight: { label: 'Минимальная высота', group: 'Расположение' },
	HorizontalLocation: { label: 'Горизонтальное положение', group: 'Расположение' },
	ThroughAlign: { label: 'Сквозное выравнивание', group: 'Расположение' },
	HeightControlVariant: { label: 'Управление высотой', group: 'Расположение' },
	Orientation: { label: 'Ориентация', group: 'Расположение' },
	ItemWidth: { label: 'Ширина элемента', group: 'Расположение' },
	ItemHeight: { label: 'Высота элемента', group: 'Расположение' },
	ItemTitleHeight: { label: 'Высота заголовка элемента', group: 'Расположение' },
	TableLocation: { label: 'Положение таблицы', group: 'Расположение' },
	CommandBarLocation: { label: 'Положение командной панели', group: 'Расположение' },
	ViewStatusLocation: { label: 'Положение состояния просмотра', group: 'Расположение' },
	SearchStringLocation: { label: 'Положение строки поиска', group: 'Расположение' },
	SearchControlLocation: { label: 'Положение управления поиском', group: 'Расположение' },
	HorizontalScrollBar: { label: 'Горизонтальная полоса прокрутки', group: 'Расположение' },
	VerticalScrollBar: { label: 'Вертикальная полоса прокрутки', group: 'Расположение' },
	WidthInMonths: { label: 'Ширина в месяцах', group: 'Расположение' },
	HeightInMonths: { label: 'Высота в месяцах', group: 'Расположение' },
	BehaviorOnHorizontalCompression: { label: 'Поведение при горизонтальном сжатии', group: 'Расположение' },
	HeaderHorizontalAlign: { label: 'Горизонтальное положение в шапке', group: 'Расположение' },
	FooterHorizontalAlign: { label: 'Горизонтальное положение в подвале', group: 'Расположение' },
	EqualItemsWidth: { label: 'Одинаковая ширина элементов', group: 'Расположение' },
	EqualColumnsWidth: { label: 'Одинаковая ширина колонок', group: 'Расположение' },

	HeaderPicture: { label: 'Картинка шапки', group: 'Оформление' },
	FooterPicture: { label: 'Картинка подвала', group: 'Оформление' },
	FooterFont: { label: 'Шрифт подвала', group: 'Оформление' },
	FooterTextColor: { label: 'Цвет текста подвала', group: 'Оформление' },
	FooterBackColor: { label: 'Цвет фона подвала', group: 'Оформление' },
	HeaderFormat: { label: 'Формат шапки', group: 'Оформление' },
	PictureSize: { label: 'Размер картинки', group: 'Оформление' },
	ImageScale: { label: 'Масштаб изображения', group: 'Оформление' },
	SelectionShowMode: { label: 'Отображение выделения', group: 'Оформление' },
	DrawingSelectionShowMode: { label: 'Отображение выделения рисунка', group: 'Оформление' },
	MarkingAppearance: { label: 'Отображение пометки', group: 'Оформление' },
	PagesRepresentation: { label: 'Отображение страниц', group: 'Оформление' },
	ViewScalingMode: { label: 'Масштаб отображения', group: 'Оформление' },
	NonselectedPictureText: { label: 'Текст невыбранной картинки', group: 'Оформление' },
	Shape: { label: 'Форма кнопки', group: 'Оформление' },
	ShapeRepresentation: { label: 'Отображение формы кнопки', group: 'Оформление' },
	PictureLocation: { label: 'Положение картинки', group: 'Оформление' },
	Hyperlink: { label: 'Гиперссылка', group: 'Оформление' },
	Hiperlink: { label: 'Гиперссылка', group: 'Оформление' },
	Wrap: { label: 'Перенос по словам', group: 'Оформление' },
	CheckBoxType: { label: 'Вид флажка', group: 'Оформление' },
	RadioButtonType: { label: 'Вид переключателя', group: 'Оформление' },
	ChoiceButtonRepresentation: { label: 'Отображение кнопки выбора', group: 'Оформление' },
	ShowHorizontalLinesFlag: { label: 'Отображать горизонтальные линии', group: 'Оформление' },
	ShowVerticalLinesFlag: { label: 'Отображать вертикальные линии', group: 'Оформление' },
	MultipleValuesHyperlink: { label: 'Гиперссылка нескольких значений', group: 'Оформление' },

	Source: { label: 'Источник', group: 'Данные' },
	AdditionSource: { label: 'Источник дополнения', group: 'Данные' },
	CommandSource: { label: 'Источник команды', group: 'Данные' },
	Parameter: { label: 'Параметр', group: 'Данные' },
	MinValue: { label: 'Минимальное значение', group: 'Данные' },
	MaxValue: { label: 'Максимальное значение', group: 'Данные' },
	HeaderDataPath: { label: 'Путь к данным шапки', group: 'Данные' },
	RowPictureDataPath: { label: 'Путь к данным картинки строки', group: 'Данные' },

	OnMainServerUnavalableBehavior: { label: 'Поведение при недоступности главного сервера', group: 'Использование' },
	PlacementArea: { label: 'Область размещения', group: 'Использование' },
	LocationInCommandBar: { label: 'Положение в командной панели', group: 'Использование' },
	RepresentationInContextMenu: { label: 'Отображение в контекстном меню', group: 'Использование' },
	OnlyInAllActions: { label: 'Только во всех действиях', group: 'Использование' },
	CommandUniqueness: { label: 'Уникальность команды', group: 'Использование' },
	DefaultButton: { label: 'Кнопка по умолчанию', group: 'Использование' },
	Check: { label: 'Пометка', group: 'Использование' },
	Output: { label: 'Вывод', group: 'Использование' },
	Edit: { label: 'Редактирование', group: 'Использование' },
	TextEdit: { label: 'Редактирование текста', group: 'Использование' },
	EditTextUpdate: { label: 'Обновление текста при редактировании', group: 'Использование' },
	IncompleteChoiceMode: { label: 'Режим выбора незаполненного', group: 'Использование' },
	AutoChoiceIncomplete: { label: 'Автовыбор незаполненного', group: 'Использование' },
	AutoAddIncomplete: { label: 'Автодобавление незаполненного', group: 'Использование' },
	ChooseType: { label: 'Выбор типа', group: 'Использование' },
	Autofill: { label: 'Автозаполнение', group: 'Использование' },
	ThreeState: { label: 'Три состояния', group: 'Использование' },
	Zoomable: { label: 'Масштабирование', group: 'Использование' },
	DropListButton: { label: 'Кнопка выпадающего списка', group: 'Использование' },
	ChoiceListButton: { label: 'Кнопка списка выбора', group: 'Использование' },
	ShowCheckBoxesInDropList: { label: 'Флажки в выпадающем списке', group: 'Использование' },
	EnableDrag: { label: 'Разрешить перетаскивание', group: 'Использование' },
	EnableStartDrag: { label: 'Разрешить начало перетаскивания', group: 'Использование' },
	FileDragMode: { label: 'Режим перетаскивания файлов', group: 'Использование' },
	CurrentRowUse: { label: 'Использование текущей строки', group: 'Использование' },
	SelectionMode: { label: 'Режим выделения', group: 'Использование' },
	RowSelectionMode: { label: 'Режим выделения строк', group: 'Использование' },
	ValuesSelectionMode: { label: 'Режим выделения значений', group: 'Использование' },
	IntervalsSelectionMode: { label: 'Режим выделения интервалов', group: 'Использование' },
	RowInputMode: { label: 'Режим ввода строк', group: 'Использование' },
	InitialListView: { label: 'Начальное отображение списка', group: 'Использование' },
	InitialTreeView: { label: 'Начальное отображение дерева', group: 'Использование' },
	RefreshRequest: { label: 'Запрос обновления', group: 'Использование' },
	UpdateOnDataChange: { label: 'Обновление при изменении данных', group: 'Использование' },
	ViewMode: { label: 'Режим просмотра', group: 'Использование' },
	SearchOnInput: { label: 'Поиск при вводе', group: 'Использование' },
	ShowCurrentDate: { label: 'Показывать текущую дату', group: 'Использование' },
	CalendarNavigation: { label: 'Навигация по календарю', group: 'Использование' },
	ShowMonthsPanel: { label: 'Показывать панель месяцев', group: 'Использование' },
	AutoShowClearButtonMode: { label: 'Автопоказ кнопки очистки', group: 'Использование' },
	AutoShowOpenButtonMode: { label: 'Автопоказ кнопки открытия', group: 'Использование' },
	SpellCheckingOnTextInput: { label: 'Проверка орфографии при вводе', group: 'Использование' },
	AutoCorrectionOnTextInput: { label: 'Автокоррекция при вводе', group: 'Использование' },
	AutoCapitalizationOnTextInput: { label: 'Регистр первых букв при вводе', group: 'Использование' },
	SpecialTextInputMode: { label: 'Специальный режим ввода текста', group: 'Использование' },
	OnScreenKeyboardReturnKeyText: { label: 'Текст клавиши возврата экранной клавиатуры', group: 'Использование' },
	AutofillHint: { label: 'Подсказка автозаполнения', group: 'Использование' },
	ChoiceHistoryOnInput: { label: 'История выбора при вводе', group: 'Использование' },
};

/** Подпись свойства: из спецификации, иначе имя узла как есть. */
export function propertyLabel(name: string): string {
	return SPEC[name]?.label ?? name;
}

/** Группа свойства: из спецификации, иначе «Прочие». */
export function propertyGroupName(name: string): PropertyGroupName {
	return SPEC[name]?.group ?? 'Прочие';
}

/**
 * Подписи констант, одинаковые у всех свойств: «да/нет/авто», стороны, использование.
 * Значения перечислений приходят от модели формата константами, а выпадающему списку нужны слова.
 */
const VALUE_LABELS: Record<string, string> = {
	true: 'Да',
	false: 'Нет',
	auto: 'Авто',
	Auto: 'Авто',
	None: 'Нет',
	Always: 'Всегда',
	Use: 'Использовать',
	DontUse: 'Не использовать',
	UseAlways: 'Использовать всегда',
	AutoUse: 'Использовать при необходимости',
	Show: 'Показывать',
	DontShow: 'Не показывать',
	WhenActive: 'При активизации',
	Left: 'Слева',
	Right: 'Справа',
	Top: 'Сверху',
	Bottom: 'Снизу',
	Center: 'По центру',
	FilledOnly: 'Только заполненное',
	Enable: 'Включено',
	Disable: 'Выключено',
	Single: 'Одиночный',
	Multiple: 'Множественный',
	Usual: 'Обычное',
};

/** Подписи констант, значение которых зависит от свойства. */
const VALUE_LABELS_BY_PROPERTY: Record<string, Record<string, string>> = {
	Group: {
		Horizontal: 'Горизонтальная',
		Vertical: 'Вертикальная',
		HorizontalIfPossible: 'Горизонтальная, если возможно',
		AlwaysHorizontal: 'Всегда горизонтальная',
		InCell: 'В ячейке',
	},
	Orientation: { Horizontal: 'Горизонтальная', Vertical: 'Вертикальная' },
	Representation: {
		Text: 'Текст',
		Picture: 'Картинка',
		PictureAndText: 'Картинка и текст',
		Compact: 'Компактное',
		List: 'Список',
		HierarchicalList: 'Иерархический список',
		Tree: 'Дерево',
		Smooth: 'Плавное',
		Broken: 'Ломаное',
		BrokenTilt: 'Ломаное с наклоном',
		StrongSeparation: 'Сильное выделение',
		WeakSeparation: 'Слабое выделение',
		NormalSeparation: 'Обычное выделение',
		GroupBox: 'Группировка',
		Line: 'Линия',
		Margin: 'Отступ',
	},
	ControlRepresentation: { TitleHyperlink: 'Гиперссылка заголовка', Picture: 'Картинка' },
	PagesRepresentation: {
		TabsOnTop: 'Закладки сверху',
		TabsOnBottom: 'Закладки снизу',
		TabsOnLeftHorizontal: 'Закладки слева горизонтально',
		TabsOnRightHorizontal: 'Закладки справа горизонтально',
		Swipe: 'Пролистывание',
	},
	Behavior: { Usual: 'Обычная', Collapsible: 'Сворачиваемая', PopUp: 'Всплывающая' },
	Type: {
		CommandBarButton: 'Кнопка командной панели',
		UsualButton: 'Обычная кнопка',
		Hyperlink: 'Гиперссылка',
		CommandBarHyperlink: 'Гиперссылка командной панели',
	},
	Shape: { Usual: 'Обычная', Oval: 'Овальная' },
	LocationInCommandBar: {
		InAdditionalSubmenu: 'В дополнительном подменю',
		InCommandBar: 'В командной панели',
		InCommandBarAndInAdditionalSubmenu: 'В командной панели и в дополнительном подменю',
	},
	RepresentationInContextMenu: {
		AdditionalInContextMenu: 'Дополнительно в контекстном меню',
		OnlyInContextMenu: 'Только в контекстном меню',
	},
	PlacementArea: {
		mainCmdsLeft: 'Основные слева',
		autoCmds: 'Автоматические',
		userCmds: 'Пользовательские',
		mainCmdsRight: 'Основные справа',
	},
	ToolTipRepresentation: {
		Balloon: 'Всплывающая',
		Button: 'Кнопка',
		ShowAuto: 'Показывать авто',
		ShowTop: 'Показывать сверху',
		ShowLeft: 'Показывать слева',
		ShowBottom: 'Показывать снизу',
		ShowRight: 'Показывать справа',
	},
	ChoiceFoldersAndItems: { Items: 'Элементы', Folders: 'Группы', FoldersAndItems: 'Группы и элементы' },
	EditMode: { Directly: 'Непосредственно', Enter: 'Ввод', EnterOnInput: 'Ввод при вводе' },
	SelectionMode: { Interval: 'Интервал', SingleRow: 'Одна строка', MultiRow: 'Несколько строк' },
	RowSelectionMode: { Cell: 'Ячейка', Row: 'Строка' },
	CheckBoxType: { CheckBox: 'Флажок', Tumbler: 'Тумблер', Switcher: 'Переключатель' },
	RadioButtonType: { RadioButtons: 'Переключатели', Tumbler: 'Тумблер' },
	HorizontalSpacing: {
		Half: 'Половинный',
		Single: 'Одинарный',
		OneAndHalf: 'Полуторный',
		Double: 'Двойной',
	},
	VerticalSpacing: {
		Half: 'Половинный',
		Single: 'Одинарный',
		OneAndHalf: 'Полуторный',
		Double: 'Двойной',
	},
	DisplayImportance: {
		VeryHigh: 'Очень высокая',
		High: 'Высокая',
		Usual: 'Обычная',
		Low: 'Низкая',
		VeryLow: 'Очень низкая',
	},
	ChildItemsWidth: {
		Equal: 'Одинаковая',
		LeftWide: 'Левая широкая',
		LeftWidest: 'Левая самая широкая',
		LeftNarrow: 'Левая узкая',
		LeftNarrowest: 'Левая самая узкая',
	},
	InitialListView: { Beginning: 'В начале', End: 'В конце' },
	InitialTreeView: {
		NoExpand: 'Не разворачивать',
		ExpandTopLevel: 'Разворачивать верхний уровень',
		ExpandAllLevels: 'Разворачивать все уровни',
	},
	RowInputMode: {
		EndOfList: 'В конец списка',
		EndOfWindow: 'В конец окна',
		AfterCurrentRow: 'После текущей строки',
		BeforeCurrentRow: 'Перед текущей строкой',
	},
	FileDragMode: { AsFile: 'Как файл', AsFileRef: 'Как ссылку на файл' },
	FixingInTable: { Left: 'Слева', Right: 'Справа' },
	PictureSize: {
		RealSize: 'Реальный размер',
		Stretch: 'Растянуть',
		Proportionally: 'Пропорционально',
		Tile: 'Замостить',
		AutoSize: 'Авторазмер',
		RealSizeIgnoreScale: 'Реальный размер без масштаба',
		AutoSizeIgnoreScale: 'Авторазмер без масштаба',
		ByFontSize: 'По размеру шрифта',
	},
	SelectionShowMode: {
		DontShow: 'Не показывать',
		WhenMultipleCellsSelected: 'При выделении нескольких ячеек',
		WhenMultipleCellsSelectedWhenActive: 'При выделении нескольких ячеек и активизации',
	},
	MarkingAppearance: { TopLeft: 'Сверху слева', BottomRight: 'Снизу справа', BothSides: 'С обеих сторон' },
	SearchStringLocation: { CommandBar: 'В командной панели', FormCaption: 'В заголовке формы', PullFromTop: 'Вытягиванием сверху' },
	SearchControlLocation: { CommandBar: 'В командной панели' },
	RefreshRequest: {
		PullFromTop: 'Вытягиванием сверху',
		PullFromBottom: 'Вытягиванием снизу',
		PullFromTopOrBottom: 'Вытягиванием сверху или снизу',
	},
	CurrentRowUse: {
		Choice: 'Выбор',
		SelectionPresentation: 'Представление выделения',
		SelectionPresentationAndChoice: 'Представление выделения и выбор',
	},
	ViewMode: { All: 'Все', QuickAccess: 'Быстрый доступ' },
	UpdateOnDataChange: { DontUpdate: 'Не обновлять' },
	BehaviorOnHorizontalCompression: {
		HideItemsByImportance: 'Скрывать по важности',
		MoveItemsByImportance: 'Переносить по важности',
	},
	OnMainServerUnavalableBehavior: { MakeDisable: 'Сделать недоступным', DontChangeBehavior: 'Не изменять поведение' },
	IncompleteChoiceMode: { OnEnterPressed: 'При нажатии Enter', OnActivate: 'При активизации' },
	EditTextUpdate: { OnValueChange: 'При изменении значения' },
	HeightControlVariant: {
		UseHeightInFormRows: 'По строкам формы',
		UseContentHeight: 'По содержимому',
		UseHeightInTableRows: 'По строкам таблицы',
	},
	ViewScalingMode: { Normal: 'Обычный', Large: 'Крупный' },
	ChoiceButtonRepresentation: {
		ShowInDropList: 'В выпадающем списке',
		ShowInDropListAndInInputField: 'В выпадающем списке и в поле ввода',
		ShowInInputField: 'В поле ввода',
	},
	ShapeRepresentation: { Always: 'Всегда', WhenActive: 'При активизации' },
	PointerType: { Special: 'Специальный', Regular: 'Обычный' },
};

/**
 * Подпись значения перечисления. Чего в словаре нет, показываем константой: словарь значений растёт
 * вместе с платформой, поэтому он заведомо неполный и это нормально.
 */
export function enumValueLabel(property: string, value: string): string {
	return VALUE_LABELS_BY_PROPERTY[property]?.[value] ?? VALUE_LABELS[value] ?? value;
}
